#!/bin/sh

userresources="$XDG_CONFIG_HOME/x11/xresources"
usermodmap="$XDG_CONFIG_HOME/x11/xmodmap"

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

pulseaudio --start &
dunst &
xwallpaper --maximize "$HOME/images/DarthVaderKill.jpg" &
exec dwm
