#!/bin/sh

userresources="$XDG_CONFIG_HOME/x11/xresources"
usermodmap="$XDG_CONFIG_HOME/x11/xmodmap"

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xwallpaper --maximize "$HOME/images/DarthVaderKill.jpg" &
exec dwm
