#!/bin/sh

userresources="$XDG_CONFIG_HOME/x11/xresources"
usermodmap="$XDG_CONFIG_HOME/x11/xmodmap"
wallpaper="$XDG_HOME/images/deathKorps.png"

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

xwallpaper --maximize "$wallpaper"
redshift -PO 4500k
exec dwm
